name: CI for Vulkan Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cmake: "3.16"
          - os: windows-latest
            cmake: "3.18"
          - os: macos-latest
            cmake: "3.18"

    steps:
    # Checkout the project repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Set up CMake on each platform
    - name: Set up CMake
      uses: lukka/get-cmake@v3
      with:
        cmake-version: ${{ matrix.cmake }}

    # Install Vulkan SDK, GLFW, GLM based on platform
    - name: Install Dependencies
      run: |
        if [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
          sudo apt update
          sudo apt install -y libglfw3-dev libglm-dev
          # Install Vulkan SDK
          sudo apt install -y vulkan-tools libvulkan-dev
        elif [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
          brew install glfw glm vulkan-headers
          # Vulkan SDK for macOS: https://vulkan.lunarg.com/sdk/home
          # Assuming you’ve already set up Vulkan SDK locally
        elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
          choco install glfw glm
          # Vulkan SDK installation on Windows using Chocolatey:
          choco install vulkan-sdk
        fi

    # Create build directory and configure CMake
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    # Cache CMake build files to speed up subsequent builds
    - name: Cache CMake
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt') }}

    # Build the project
    - name: Build
      run: |
        cd build
        cmake --build .

    # Run tests if your project has tests
    - name: Run Tests
      run: |
        cd build
        ctest
